name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e blender_addon[dev]

      - name: Run markdown linter
        run: |
          python blender_addon/scripts/markdown_lint.py

      - name: Ruff Lint
        run: ruff check .

      - name: Run tests with coverage
        run: pytest
